models/saved_doc.py
"""
This module contains the model object for saved documents.
"""

import datetime
from typing import List, Tuple

import pytz as pytz
from sqlalchemy import Column, Integer, ForeignKey, Text, TIMESTAMP
from sqlalchemy.dialects.postgresql import ARRAY

from utils.application_factories.database import db


class SavedDoc(db.Model):
    """
    Postgres model for Saved Document
    """
    __tablename__ = 'saved_docs'
    id = Column(Integer, primary_key=True)
    creator_id = Column(Integer, ForeignKey('users.id'))
    title = Column(Text, nullable=False)
    doc_summary = Column(Text, nullable=False)
    doc_events = Column(ARRAY(Text))
    doc_created_date = Column(TIMESTAMP(timezone=False), default=datetime.datetime.utcnow().replace(tzinfo=pytz.UTC))

    def __init__(self, creator_id: int, title: str, doc_summary: str, doc_events: List[Tuple[datetime, str, str]]):
        self.creator_id = creator_id
        self.title = title
        self.doc_summary = doc_summary
        self.doc_events = doc_events

models/users.py
"""
This module contains the model object for users.
"""
from flask_login import UserMixin
from sqlalchemy import Column, Integer, String
from utils.application_factories.database import db


class User(db.Model, UserMixin):
    """
    Postgres model for users
    """
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    username = Column(String(50), unique=True)
    password = Column(String(128))

    def __init__(self, username=None, password=None):
        self.username = username
        self.password = password

    def __repr__(self):
        return '<User %r>' % (self.username)

forms.py
"""
This module contains forms for templates
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, EqualTo


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    username = StringField('Username', [Length(min=4, max=25)])
    password = PasswordField('New Password', [
        DataRequired(),
        EqualTo('confirm', message='Passwords must match')
    ])
    confirm = PasswordField('Repeat Password')
    submit = SubmitField('Sign Up')


class DocumentForm(FlaskForm):
    title = StringField('Article Title', [Length(min=4, max=25)])
    article = TextAreaField('Article Text', render_kw={"rows": 20, "cols": 70})
    submit = SubmitField('Generate')

app.py
import os

from flask import Flask

from auth import auth
from doc import doc
from home import homes
from utils.application_factories.database import db
from services import user_service
from utils.application_factories.login import login_manager


def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ['SQLALCHEMY_DATABASE_URI']
    app.config['SECRET_KEY'] = os.environ['SECRET_KEY']
    db.init_app(app)
    login_manager.init_app(app)
    app.register_blueprint(homes)
    app.register_blueprint(auth)
    app.register_blueprint(doc)

    return app


@login_manager.user_loader
def load_user(user_id):
    return user_service.get_user_by_id(user_id)


def setup_database(app):
    with app.app_context():
        db.create_all()


if __name__ == '__main__':
    app = create_app()
    setup_database(app)
    app.run(host="0.0.0.0")

auth.py
"""
This module defines blueprint for authorization
"""

from flask import Blueprint, render_template
from flask_login import login_user, current_user, login_required, logout_user
from werkzeug.security import check_password_hash

from forms import LoginForm, RegistrationForm
from models.users import User
from services import user_service

auth = Blueprint('auth', __name__, template_folder='templates/auth')


@auth.route('/register', methods=('POST', 'GET'))
def register():
    """
    User Registration endpoint
    """
    if current_user.is_authenticated:
        return render_template('index.html')
    form = RegistrationForm()
    if form.validate_on_submit():
        user = user_service.get_user_by_username(username=form.username.data)
        if user is None:
            user_service.create_new_user(username=form.username.data, password=form.password.data)
            return render_template('index.html')
        else:
            error = 'Unable to create user. Please try again.'
            return render_template('register.html', form=form, error=error)
    return render_template('register.html', form=form)


@auth.route('/login', methods=('POST', 'GET'))
def login():
    """
    Login endpoint
    :return:
    """
    if current_user.is_authenticated:
        return render_template('index.html')
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not check_password_hash(user.password, form.password.data):
            error = 'Invalid username or password'
            return render_template('login.html', error=error, form=form)
        login_user(user, remember=form.remember_me.data)
        return render_template('index.html', is_index=True)
    return render_template('login.html', form=form)


@auth.route("/logout")
@login_required
def logout():
    """
    Logout endpoint
    :return:
    """
    logout_user()
    return render_template('index.html')

utils/blueprint_constants.py
TRANSLATIONS = 'translations'
TEXT = 'text'
DOC_SUMMARY = "doc_summary"
DOC_EVENTS = "doc_events"

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Project History Babel</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
</head>

<body>
<section class="hero is-fullheight">

    <div class="hero-head">

        <nav class="level">
            <div class="level-left">
                {% if not is_index %}
                <div class="level-item">
                    <p class="subtitle is-5">
                        Project History Babel
                    </p>
                </div>
                {% endif %}

            </div>
            <div class="level-right">
                {% if current_user.is_authenticated %}

                {% if not is_index %}
                <p class="level-item ">
                    <a class="link is-info" href="{{ url_for('homes.home') }}">Home</a>
                </p>
                {% endif %}

                <p class="level-item ">
                    <a class="link is-info" href="{{ url_for('doc.get_saved_doc_list') }}">Saved Documents</a>
                </p>
                <p class="level-item">
                    <a class="link is-info" href="{{ url_for('doc.create_doc') }}">Add New</a>
                </p>
                <p class=" level-item ">
                    <a href="/logout" class="navbar-item">
                        Logout
                    </a>
                </p>
                {% else %}
                <p class="level-item ">
                    <a href="{{ url_for('auth.login') }}" class="navbar-item">
                        Login
                    </a>
                </p>
                <p class="level-item ">
                    <a href="{{ url_for('auth.register') }}" class="navbar-item">
                        Sign Up
                    </a>
                </p>
                {% endif %}
            </div>
        </nav>
    </div>
    </nav>
    </div>
    <div class="container is-primary has-text-centered">

    </div>
    <div class="hero-body">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</section>
<script src="http://code.jquery.com/jquery.js"></script>
<script src="{{ url_for('static', filename='app.js') }}"></script>

</body>

</html>

templates/doc/create.html
{% extends "base.html" %}

{% block content %}
<div class="columns">
    <div class="column">
        <div class="box">
            <h4 class="title is-4">Article</h4>
            <p>
                <label for="title">Article Title</label><br>
                <input class="input is-left is-primary" type="text" id="title" name="title" autofocus>
            </p>
            <br>
            <p>
                <label for="article">Article Text</label><br>
                <textarea id="article" class="textarea is-small" rows="10" cols="50"></textarea>
            </p>
            <br>
            <button class="button is-primary is-light" id="generate_button">Generate</button>
        </div>
    </div>
    <div class="column">
        <div id="summary_box" class="box" style="display:none">
            <h4 class="title is-4">Article Summary</h4>
            <div id="summary" class="box">
            </div>
        </div>
    </div>
    <div class="column">
        <div id="event_box" class="box" style="display:none">
            <h4 class="title is-4">Article Events</h4>
            <table class="table is-fullwidth" id="event">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Event</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/doc/doc_list.html
{% extends "base.html" %}

{% block content %}
<div id="event_box" class="box">
    <table class="table is-fullwidth" id="event">
        <thead>
        <tr>
            <th>Document Title</th>
            <th>Date Created</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for item in doc_list %}
        <tr>
            <td><a href="{{ url_for('doc.get_saved_doc', doc_id=item.id) }}"> {{ item.title }}</a>
            </td>
            <td>{{ item.doc_created_date }}</td>
            <td><a data-confirm="Are you sure?" data-method="delete"
                   href="{{ url_for('doc.delete_saved_doc',doc_id=item.id) }}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/doc/saved_doc.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">{{ doc.title }}</h1>

<div class="columns">
    <div class="column">
        <div id="summary_box" class="box">
            {{ doc.doc_summary }}
        </div>
    </div>
    <div class="column">
        <div id="event_box" class="box">
            <table class="table is-fullwidth" id="event">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Event</th>
                </tr>
                </thead>
                <tbody>
                {% for item in doc.doc_events %}
                <tr>
                    <td>{{ item[1] }}</td>
                    <td>{{ item[2] }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Project History Babel
</h1>
<h2 class="subtitle">
  Get summary and important events extracted from historical documents
</h2>
{% endblock %}